[tool.poetry]
name = "acdcpp"
version = "0.1.0"
description = ""
authors = ["Aaquib, Can, Arthur"]
readme = "README.md"
packages = [{include = "acdcpp"}]

[tool.poetry.dependencies]
python = "^3.8"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
